// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSHrYJ-UEpGThmSf4GtbVQr6DjvhsCIm4',
    appId: '1:379616346839:web:413e4863a2689880bd2692',
    messagingSenderId: '379616346839',
    projectId: 'push-notification-3fa23',
    authDomain: 'push-notification-3fa23.firebaseapp.com',
    databaseURL: 'https://push-notification-3fa23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'push-notification-3fa23.appspot.com',
    measurementId: 'G-RS77DPHP0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgl_5sN6czkcOxmFZ3dqhnoMfYZGNfEVM',
    appId: '1:379616346839:android:6ea35dcaa29a737ebd2692',
    messagingSenderId: '379616346839',
    projectId: 'push-notification-3fa23',
    databaseURL: 'https://push-notification-3fa23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'push-notification-3fa23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1W4y5y3vLwAPTSAB_DyQwY1KOcXrAwMg',
    appId: '1:379616346839:ios:95f34b5d315a1a41bd2692',
    messagingSenderId: '379616346839',
    projectId: 'push-notification-3fa23',
    databaseURL: 'https://push-notification-3fa23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'push-notification-3fa23.appspot.com',
    androidClientId: '379616346839-dr1rmohcbspisrh65igr175j64bop6uc.apps.googleusercontent.com',
    iosClientId: '379616346839-diqg4rqlo9g376sc788un3oot4frhoec.apps.googleusercontent.com',
    iosBundleId: 'com.thetork.kireibd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1W4y5y3vLwAPTSAB_DyQwY1KOcXrAwMg',
    appId: '1:379616346839:ios:95f34b5d315a1a41bd2692',
    messagingSenderId: '379616346839',
    projectId: 'push-notification-3fa23',
    databaseURL: 'https://push-notification-3fa23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'push-notification-3fa23.appspot.com',
    androidClientId: '379616346839-dr1rmohcbspisrh65igr175j64bop6uc.apps.googleusercontent.com',
    iosClientId: '379616346839-diqg4rqlo9g376sc788un3oot4frhoec.apps.googleusercontent.com',
    iosBundleId: 'com.thetork.kireibd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSHrYJ-UEpGThmSf4GtbVQr6DjvhsCIm4',
    appId: '1:379616346839:web:d04911798cb375a7bd2692',
    messagingSenderId: '379616346839',
    projectId: 'push-notification-3fa23',
    authDomain: 'push-notification-3fa23.firebaseapp.com',
    databaseURL: 'https://push-notification-3fa23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'push-notification-3fa23.appspot.com',
    measurementId: 'G-VZGD4JD610',
  );

}