// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTn2cddVXbVVvpjajAqz6CyDmHHPC6mE',
    appId: '1:547850683072:web:ef2233d641e0e5f974e325',
    messagingSenderId: '547850683072',
    projectId: 'app-boilerplate-8f2ca',
    authDomain: 'app-boilerplate-8f2ca.firebaseapp.com',
    storageBucket: 'app-boilerplate-8f2ca.appspot.com',
    measurementId: 'G-9LV18CH651',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbNVkYTBw1Oyx8jrEisTx6PHvb1Ccycd8',
    appId: '1:547850683072:android:c466642af1f3a41c74e325',
    messagingSenderId: '547850683072',
    projectId: 'app-boilerplate-8f2ca',
    storageBucket: 'app-boilerplate-8f2ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iUBdrqe7hRTszKOZPyBrPcfbQQ-OUO4',
    appId: '1:547850683072:ios:897898b48a9505f774e325',
    messagingSenderId: '547850683072',
    projectId: 'app-boilerplate-8f2ca',
    storageBucket: 'app-boilerplate-8f2ca.appspot.com',
    androidClientId: '547850683072-ghibuud3arbjkr27o5uhp4g1ev4s1quf.apps.googleusercontent.com',
    iosClientId: '547850683072-qeq9v7uitbsie821ccfis7idkjpierpi.apps.googleusercontent.com',
    iosBundleId: 'com.thetork.kirei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iUBdrqe7hRTszKOZPyBrPcfbQQ-OUO4',
    appId: '1:547850683072:ios:897898b48a9505f774e325',
    messagingSenderId: '547850683072',
    projectId: 'app-boilerplate-8f2ca',
    storageBucket: 'app-boilerplate-8f2ca.appspot.com',
    androidClientId: '547850683072-ghibuud3arbjkr27o5uhp4g1ev4s1quf.apps.googleusercontent.com',
    iosClientId: '547850683072-qeq9v7uitbsie821ccfis7idkjpierpi.apps.googleusercontent.com',
    iosBundleId: 'com.thetork.kirei',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUTn2cddVXbVVvpjajAqz6CyDmHHPC6mE',
    appId: '1:547850683072:web:b22900426b5542a374e325',
    messagingSenderId: '547850683072',
    projectId: 'app-boilerplate-8f2ca',
    authDomain: 'app-boilerplate-8f2ca.firebaseapp.com',
    storageBucket: 'app-boilerplate-8f2ca.appspot.com',
    measurementId: 'G-RJNWBVC0HZ',
  );

}