
class BlogsDummyData{

  String? postTime;
  String? title;
  String? backgroundImage;
  String? authorName;
  String? authorDesignation;
  String? timeToRead;
  String? postDescription;

  BlogsDummyData(
      {this.postTime,
      this.title,
      this.backgroundImage,
      this.authorName,
      this.authorDesignation,
      this.timeToRead,
      this.postDescription});

  static List<BlogsDummyData> blogList = [
    BlogsDummyData(title: "Strategies For Personal And Professionalism", authorName: "John Smith", postTime: "2 days ago", timeToRead: "12 mins to read", authorDesignation: "Product Designer", backgroundImage: "assets/images/products/blog.png", postDescription: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident.",),
    BlogsDummyData(title: "Practical Tips And Strategies For Effective", authorName: "Ross Taylor", postTime: "24 March, 2024", timeToRead: "8 mins to read", authorDesignation: "Graphics Designer", backgroundImage: "assets/images/products/blog1.png", postDescription: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",),
    BlogsDummyData(title: "Insights And Advice For Continues soul", authorName: "James Vince", postTime: "12 February, 2024", timeToRead: "15 mins to read", authorDesignation: "Web Designer", backgroundImage: "assets/images/products/blog2.png", postDescription: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, comes from a line in section 1.10.32.",),
    BlogsDummyData(title: "Strategies For Personal And Professionalism", authorName: "Kelvin Petersion", postTime: "8 February, 2024", timeToRead: "9 mins to read", authorDesignation: "Ui/Ux Designer", backgroundImage: "assets/images/products/blog.png", postDescription: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",),
    BlogsDummyData(title: "Strategies For Personal And Professionalism", authorName: "Gray Kristian", postTime: "5 February, 2024", timeToRead: "5 mins to read", authorDesignation: "App Developer", backgroundImage: "assets/images/products/blog1.png", postDescription: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",),
    BlogsDummyData(title: "Strategies For Personal And Professionalism", authorName: "Rovman paul", postTime: "3 February, 2024", timeToRead: "20 mins to read", authorDesignation: "Game Developer", backgroundImage: "assets/images/products/blog2.png", postDescription: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident.",),
    BlogsDummyData(title: "Strategies For Personal And Professionalism", authorName: "Kemo paul", postTime: "2 February, 2024", timeToRead: "22 mins to read", authorDesignation: "Content Writing", backgroundImage: "assets/images/products/blog.png", postDescription: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident.",),
    BlogsDummyData(title: "Strategies For Personal And Professionalism", authorName: "Jp Dummny", postTime: "1 February, 2024", timeToRead: "7 mins to read", authorDesignation: "Fashion Designer", backgroundImage: "assets/images/products/blog1.png", postDescription: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident.",),


  ];
}